const subject = [
  { id: crypto.randomUUID(), name: 'Matematicas' },
  { id: crypto.randomUUID(), name: 'Tecnologías de la Información' },
  { id: crypto.randomUUID(), name: 'Arquitectura del computador' },
  { id: crypto.randomUUID(), name: 'Ingles' },
  { id: crypto.randomUUID(), name: 'Electronica' },
  { id: crypto.randomUUID(), name: 'Electiva' },
  { id: crypto.randomUUID(), name: 'FrameWork' },
  { id: crypto.randomUUID(), name: 'Programación' },
  { id: crypto.randomUUID(), name: 'Proyecto Sociotecnico' },
  { id: crypto.randomUUID(), name: 'Sistemas Operativos' },
  { id: crypto.randomUUID(), name: 'Física' },
  { id: crypto.randomUUID(), name: 'Química' },
  { id: crypto.randomUUID(), name: 'Biología' },
  { id: crypto.randomUUID(), name: 'Historia' },
  { id: crypto.randomUUID(), name: 'Geografía' },
  { id: crypto.randomUUID(), name: 'Economía' },
  { id: crypto.randomUUID(), name: 'Sociología' },
  { id: crypto.randomUUID(), name: 'Psicología' },
  { id: crypto.randomUUID(), name: 'Filosofía' },
  { id: crypto.randomUUID(), name: 'Arte' },
  { id: crypto.randomUUID(), name: 'Danza' },
  { id: crypto.randomUUID(), name: 'Literatura' },
  { id: crypto.randomUUID(), name: 'Educación Física' },
  { id: crypto.randomUUID(), name: 'Salud y Nutrición' },
  { id: crypto.randomUUID(), name: 'Emprendimiento' },
  { id: crypto.randomUUID(), name: 'Derecho' },
  { id: crypto.randomUUID(), name: 'Administración' },
  { id: crypto.randomUUID(), name: 'Contabilidad' },
  { id: crypto.randomUUID(), name: 'Mercadotecnia' },
  { id: crypto.randomUUID(), name: 'Recursos Humanos' },
  { id: crypto.randomUUID(), name: 'Finanzas' },
  { id: crypto.randomUUID(), name: 'Logística' },
  { id: crypto.randomUUID(), name: 'Negocios Internacionales' },
  { id: crypto.randomUUID(), name: 'Diseño Gráfico' },
  { id: crypto.randomUUID(), name: 'Multimedia' },
  { id: crypto.randomUUID(), name: 'Animación' },
  { id: crypto.randomUUID(), name: 'Fotografía' },
  { id: crypto.randomUUID(), name: 'Publicidad' },
  { id: crypto.randomUUID(), name: 'Periodismo' },
  { id: crypto.randomUUID(), name: 'Relaciones Públicas' },
  { id: crypto.randomUUID(), name: 'Producción Audiovisual' },
  { id: crypto.randomUUID(), name: 'Ingeniería Civil' },
  { id: crypto.randomUUID(), name: 'Ingeniería Mecánica' },
  { id: crypto.randomUUID(), name: 'Ingeniería Eléctrica' },
  { id: crypto.randomUUID(), name: 'Ingeniería Industrial' },
  { id: crypto.randomUUID(), name: 'Ingeniería Química' },
  { id: crypto.randomUUID(), name: 'Ingeniería Ambiental' },
  { id: crypto.randomUUID(), name: 'Medicina' },
  { id: crypto.randomUUID(), name: 'Enfermería' },
  { id: crypto.randomUUID(), name: 'Farmacia' },
  { id: crypto.randomUUID(), name: 'Odontología' },
  { id: crypto.randomUUID(), name: 'Veterinaria' },
  { id: crypto.randomUUID(), name: 'Psicología Clínica' },
  { id: crypto.randomUUID(), name: 'Trabajo Social' },
  { id: crypto.randomUUID(), name: 'Educación' },
  { id: crypto.randomUUID(), name: 'Derecho Penal' },
  { id: crypto.randomUUID(), name: 'Criminología' },
  { id: crypto.randomUUID(), name: 'Relaciones Internacionales' },
  { id: crypto.randomUUID(), name: 'Turismo' },
  { id: crypto.randomUUID(), name: 'Gastronomía' },
  { id: crypto.randomUUID(), name: 'Deportes' },
  { id: crypto.randomUUID(), name: 'Artes Escénicas' },
  { id: crypto.randomUUID(), name: 'Música' },
  { id: crypto.randomUUID(), name: 'Bellas Artes' },
  { id: crypto.randomUUID(), name: 'Comunicación' },
  { id: crypto.randomUUID(), name: 'Informática' },
  { id: crypto.randomUUID(), name: 'Ingeniería de Sistemas' }
]

export default subject
