const teachers = [
  { id: crypto.randomUUID(), name: 'Javier', last_name: 'Martiño', ci: '12345678', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'María', last_name: 'Gómez', ci: '87654321', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Juan', last_name: 'Pérez', ci: '13579086', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Ana', last_name: 'Rodríguez', ci: '24680197', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Carlos', last_name: 'Sánchez', ci: '31415926', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Sofía', last_name: 'Martínez', ci: '65432109', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Diego', last_name: 'Gutiérrez', ci: '98765432', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Lucía', last_name: 'Fernández', ci: '14725836', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Andrés', last_name: 'Morales', ci: '78963214', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Natalia', last_name: 'Herrera', ci: '12345987', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Alejandro', last_name: 'Vargas', ci: '65789012', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Gabriela', last_name: 'Jiménez', ci: '32145678', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Fernando', last_name: 'Reyes', ci: '45678901', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Claudia', last_name: 'Rojas', ci: '78901234', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Raúl', last_name: 'Torres', ci: '56789012', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Valeria', last_name: 'Castillo', ci: '34567890', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Daniel', last_name: 'Rivas', ci: '67890123', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Paola', last_name: 'Gómez', ci: '89012345', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Enrique', last_name: 'Ortiz', ci: '23456789', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Camila', last_name: 'Núñez', ci: '45670123', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Miguel', last_name: 'Hernández', ci: '78901256', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Isabel', last_name: 'Flores', ci: '34567891', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Jorge', last_name: 'Guzmán', ci: '67890124', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Emilia', last_name: 'Ramírez', ci: '12345677', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Sergio', last_name: 'Campos', ci: '98765430', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Lorena', last_name: 'Vargas', ci: '45678900', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Eduardo', last_name: 'Rojas', ci: '78901231', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Gabriela', last_name: 'Jiménez', ci: '32145676', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Fernando', last_name: 'Reyes', ci: '45678911', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Claudia', last_name: 'Rojas', ci: '78901230', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Raúl', last_name: 'Torres', ci: '56789011', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Valeria', last_name: 'Castillo', ci: '34567892', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Daniel', last_name: 'Rivas', ci: '67890125', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Paola', last_name: 'Gómez', ci: '89012344', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Enrique', last_name: 'Ortiz', ci: '23456790', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Camila', last_name: 'Núñez', ci: '45670124', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Miguel', last_name: 'Hernández', ci: '78901257', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Isabel', last_name: 'Flores', ci: '34567893', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Jorge', last_name: 'Guzmán', ci: '67890126', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Emilia', last_name: 'Ramírez', ci: '12345674', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Sergio', last_name: 'Campos', ci: '98765433', title: 'Profesor' },
  { id: crypto.randomUUID(), name: 'Lorena', last_name: 'Vargas', ci: '45678902', title: 'Profesora' },
  { id: crypto.randomUUID(), name: 'Eduardo', last_name: 'Rojas', ci: '78901235', title: 'Profesor' }
]

export default teachers
