export const subjectsList = [
  { id: '1', subject: 'Math', hours: 5, pnf: 'Informatica', seccion: '1', quarter: [1, 2, 3] },
  { id: '2', subject: 'Physics', hours: 8, pnf: 'Administracion', seccion: '1', quarter: [2, 3] },
  { id: '3', subject: 'English', hours: 4, pnf: 'Agronomia', seccion: '1', quarter: [1, 2] },
  { id: '4', subject: 'Literature', hours: 6, pnf: 'Informatica', seccion: '1', quarter: [1] },
  { id: '5', subject: 'Historia', hours: 6, pnf: 'Informatica', seccion: '2', quarter: [1, 2] },
  { id: '6', subject: 'Spanish', hours: 4, pnf: 'Administracion', seccion: '2', quarter: [2, 3] },
  { id: '7', subject: 'Latin American Literature', hours: 4, pnf: 'Informatica', seccion: '1', quarter: [3] },
  { id: '8', subject: 'Business Management', hours: 8, pnf: 'Administracion', seccion: '2', quarter: [3] },
  { id: '9', subject: 'Chemistry', hours: 7, pnf: 'Quimica', seccion: '1', quarter: [3] },
  { id: '10', subject: 'Biology', hours: 6, pnf: 'Biologia', seccion: '1', quarter: [1, 2] },
  { id: '11', subject: 'Computer Science', hours: 8, pnf: 'Informatica', seccion: '2', quarter: [1, 2] },
  { id: '12', subject: 'Art History', hours: 4, pnf: 'Artes', seccion: '1', quarter: [2, 3] },
  { id: '13', subject: 'Music Theory', hours: 5, pnf: 'Artes', seccion: '1', quarter: [1, 2] },
  { id: '14', subject: 'Sociology', hours: 6, pnf: 'Ciencias Sociales', seccion: '1', quarter: [] },
  { id: '15', subject: 'Psychology', hours: 6, pnf: 'Ciencias Sociales', seccion: '2', quarter: [2] },
  { id: '16', subject: 'Anthropology', hours: 5, pnf: 'Ciencias Sociales', seccion: '1', quarter: [2] },
  { id: '17', subject: 'Philosophy', hours: 4, pnf: 'Humanidades', seccion: '1', quarter: [2, 3] },
  { id: '18', subject: 'Ethics', hours: 4, pnf: 'Humanidades', seccion: '2', quarter: [1, 2] },
  { id: '19', subject: 'Calculus', hours: 7, pnf: 'Matematicas', seccion: '1', quarter: [1, 2, 3] },
  { id: '20', subject: 'Discrete Mathematics', hours: 6, pnf: 'Matematicas', seccion: '2', quarter: [1] },
  { id: '21', subject: 'Mechanical Engineering', hours: 8, pnf: 'Ingenieria', seccion: '1', quarter: [2] },
  { id: '22', subject: 'Electrical Engineering', hours: 8, pnf: 'Ingenieria', seccion: '2', quarter: [3] },
  { id: '23', subject: 'Civil Engineering', hours: 8, pnf: 'Ingenieria', seccion: '1', quarter: [1, 2] },
  { id: '24', subject: 'Aerospace Engineering', hours: 8, pnf: 'Ingenieria', seccion: '2', quarter: [3] },
  { id: '25', subject: 'Environmental Science', hours: 6, pnf: 'Ciencias Ambientales', seccion: '1', quarter: [1, 2] },
  { id: '26', subject: 'Ecology', hours: 6, pnf: 'Ciencias Ambientales', seccion: '2', quarter: [3] },
  { id: '27', subject: 'Oceanography', hours: 6, pnf: 'Ciencias Ambientales', seccion: '1', quarter: [2] },
  { id: '28', subject: 'Astronomy', hours: 5, pnf: 'Ciencias Fisicas', seccion: '1', quarter: [1] },
  { id: '29', subject: 'Geology', hours: 6, pnf: 'Ciencias Geologicas', seccion: '1', quarter: [1, 2] },
  { id: '30', subject: 'Meteorology', hours: 6, pnf: 'Ciencias Atmosfericas', seccion: '1', quarter: [1, 2, 3] },
  { id: '31', subject: 'Nutrition', hours: 5, pnf: 'Ciencias de la Salud', seccion: '1', quarter: [2, 3] },
  { id: '32', subject: 'Anatomy', hours: 6, pnf: 'Ciencias de la Salud', seccion: '2', quarter: [1, 2] },
  { id: '33', subject: 'Physiology', hours: 6, pnf: 'Ciencias de la Salud', seccion: '1', quarter: [3] },
  { id: '34', subject: 'Pharmacology', hours: 6, pnf: 'Ciencias de la Salud', seccion: '2', quarter: [2, 3] },
  { id: '35', subject: 'Accounting', hours: 6, pnf: 'Administracion', seccion: '1', quarter: [3] },
  { id: '36', subject: 'Finance', hours: 6, pnf: 'Administracion', seccion: '2', quarter: [1, 2] },
  { id: '37', subject: 'Marketing', hours: 6, pnf: 'Administracion', seccion: '1', quarter: [3] },
  { id: '38', subject: 'Economics', hours: 6, pnf: 'Administracion', seccion: '2', quarter: [1, 2, 3] },
  { id: '39', subject: 'Business Law', hours: 4, pnf: 'Administracion', seccion: '1', quarter: [3] },
  { id: '40', subject: 'Entrepreneurship', hours: 4, pnf: 'Administracion', seccion: '2', quarter: [1] },
  { id: '41', subject: 'Journalism', hours: 5, pnf: 'Comunicaciones', seccion: '1', quarter: [3] },
  { id: '42', subject: 'Communications', hours: 5, pnf: 'Comunicaciones', seccion: '2', quarter: [3] },
  { id: '43', subject: 'Public Speaking', hours: 4, pnf: 'Comunicaciones', seccion: '1', quarter: [2, 3] },
  { id: '44', subject: 'Media Studies', hours: 4, pnf: 'Comunicaciones', seccion: '2', quarter: [2, 3] },
  { id: '45', subject: 'Photography', hours: 5, pnf: 'Artes', seccion: '2', quarter: [2, 3] },
  { id: '46', subject: 'Graphic Design', hours: 6, pnf: 'Artes', seccion: '1', quarter: [1] },
  { id: '47', subject: 'Film Studies', hours: 5, pnf: 'Artes', seccion: '2', quarter: [3] },
  { id: '48', subject: 'Creative Writing', hours: 4, pnf: 'Humanidades', seccion: '1', quarter: [2] },
  { id: '49', subject: 'World History', hours: 6, pnf: 'Historia', seccion: '1', quarter: [2] },
  { id: '50', subject: 'American History', hours: 6, pnf: 'Historia', seccion: '2', quarter: [3] }
]
