export const teachersList = [
  {
    id: 'yo',
    name: 'John',
    lastName: 'Doe',
    ci: '12345678',
    type: 'full-time',
    photo: null,
    title: 'Professor',
    partTime: 16,
    load: [],
    perfil: ['5', '6', '7'],
    gender: 'm'
  },
  {
    id: '2',
    name: 'Jane',
    lastName: 'Smith',
    ci: '87654321',
    type: 'part-time',
    photo: null,
    title: 'Lecturer',
    partTime: 10,
    load: [],
    perfil: ['1', '2', '3'],
    gender: 'f'
  },
  {
    id: '3',
    name: 'Michael',
    lastName: 'Johnson',
    ci: '24681012',
    type: 'full-time',
    photo: null,
    title: 'Associate Professor',
    partTime: 18,
    load: [],
    perfil: ['3', '4'],
    gender: 'm'
  },
  {
    id: '4',
    name: 'Emily',
    lastName: 'Davis',
    ci: '13579246',
    type: 'part-time',
    photo: null,
    title: 'Adjunct Professor',
    partTime: 6,
    load: [],
    perfil: ['5', '6', '7', '8'],
    gender: 'f'
  },
  {
    id: '5',
    name: 'David',
    lastName: 'Lee',
    ci: '24681357',
    type: 'full-time',
    photo: null,
    title: 'Professor',
    partTime: 20,
    load: [],
    perfil: ['9', '10'],
    gender: 'm'
  },
  {
    id: '6',
    name: 'Sophia',
    lastName: 'Gonzalez',
    ci: '97531486',
    type: 'part-time',
    photo: null,
    title: 'Lecturer',
    partTime: 8,
    load: [],
    perfil: ['9', '10', '11', '12'],
    gender: 'f'
  },
  {
    id: '7',
    name: 'Alexander',
    lastName: 'Müller',
    ci: '86420159',
    type: 'full-time',
    photo: null,
    title: 'Associate Professor',
    partTime: 22,
    load: [],
    perfil: ['13', '14'],
    gender: 'm'
  },
  {
    id: '8',
    name: 'Olivia',
    lastName: 'Fernandez',
    ci: '47853912',
    type: 'part-time',
    photo: null,
    title: 'Lecturer',
    partTime: 12,
    load: [],
    perfil: ['15', '16', '18'],
    gender: 'f'
  },
  {
    id: '9',
    name: 'William',
    lastName: 'Rodriguez',
    ci: '31975842',
    type: 'full-time',
    photo: null,
    title: 'Professor',
    partTime: 24,
    load: [],
    perfil: ['Experienced', 'Research-oriented'],
    gender: 'm'
  },
  {
    id: '10',
    name: 'Isabella',
    lastName: 'Nguyen',
    ci: '64782910',
    type: 'part-time',
    photo: null,
    title: 'Lecturer',
    partTime: 10,
    load: [],
    perfil: ['Passionate', 'Innovative'],
    gender: 'f'
  },
  {
    id: '11',
    name: 'Daniel',
    lastName: 'Patel',
    ci: '85231746',
    type: 'full-time',
    photo: null,
    title: 'Associate Professor',
    partTime: 20,
    load: [],
    perfil: ['Experienced', 'Researcher'],
    gender: 'm'
  },
  {
    id: '12',
    name: 'Ava',
    lastName: 'Hernandez',
    ci: '73495128',
    type: 'part-time',
    photo: null,
    title: 'Lecturer',
    partTime: 8,
    load: [],
    perfil: ['1', '22', '23', '24'],
    gender: 'f'
  },
  {
    id: '13',
    name: 'Jacob',
    lastName: 'Saito',
    ci: '92617534',
    type: 'full-time',
    photo: null,
    title: 'Professor',
    partTime: 22,
    load: [],
    perfil: ['23', '24', '25', '26'],
    gender: 'm'
  },
  {
    id: '14',
    name: 'Emma',
    lastName: 'Tanaka',
    ci: '48375612',
    type: 'part-time',
    photo: null,
    title: 'Lecturer',
    partTime: 18,
    load: [],
    perfil: ['5', '6', '7'],
    gender: 'f'
  },
  {
    id: '15',
    name: 'Ethan',
    lastName: 'Morales',
    ci: '71928354',
    type: 'full-time',
    photo: null,
    title: 'Associate Professor',
    partTime: 24,
    load: [],
    perfil: ['5', '6', '7'],
    gender: 'm'
  }
]
